services:
  frontend:
    container_name: classhero-frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - app_net

  backend:
    container_name: classhero-backend
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    working_dir: /workspace/backend
    volumes:
      - ./backend:/workspace/backend
      - ./frontend:/workspace/frontend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    command: sleep infinity
    networks:
      - app_net

  proxy:
    container_name: classhero-proxy
    build:
      context: .
      dockerfile: ./frontend-infra/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
